<?php

namespace Database\Seeders;

use App\Models\User;
use DB;
use Exception;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    try {
      if (DB::table('users')->count() == 0) {
        DB::table('users')->insert([
          [
            'first_name' => 'John',
            'last_name' => 'Doe',
            'gender' => 'Male',
            'status' => 'Active',
            'role' => 'Agent',
            'dob' => '07/15/2024',
            'contact_no' => '971525698745',
            'home_address' => 'H # 12, Street 20, Lalazar',
            'email' => 'john@gmail.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Jane',
            'last_name' => 'Smith',
            'gender' => 'Female',
            'status' => 'Active',
            'role' => 'Manager',
            'dob' => '08/22/1988',
            'contact_no' => '971555123456',
            'home_address' => 'H # 34, Street 12, Downtown',
            'email' => 'jane.smith@example.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Michael',
            'last_name' => 'Brown',
            'gender' => 'Male',
            'status' => 'Block',
            'role' => 'Staff',
            'dob' => '12/10/1975',
            'contact_no' => '971522345678',
            'home_address' => 'H # 56, Street 8, Uptown',
            'email' => 'michael.brown@example.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Emily',
            'last_name' => 'Davis',
            'gender' => 'Female',
            'status' => 'Active',
            'role' => 'Staff',
            'dob' => '05/30/1992',
            'contact_no' => '971523456789',
            'home_address' => 'H # 78, Street 14, Green Town',
            'email' => 'emily.davis@example.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Chris',
            'last_name' => 'Wilson',
            'gender' => 'Male',
            'status' => 'Active',
            'role' => 'Staff',
            'dob' => '11/19/1985',
            'contact_no' => '971554321234',
            'home_address' => 'H # 23, Street 9, River Side',
            'email' => 'chris.wilson@example.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Sarah',
            'last_name' => 'Martinez',
            'gender' => 'Female',
            'status' => 'Active',
            'role' => 'Agent',
            'dob' => '03/14/1978',
            'contact_no' => '971556789012',
            'home_address' => 'H # 45, Street 6, Lake View',
            'email' => 'sarah.martinez@example.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'David',
            'last_name' => 'Miller',
            'gender' => 'Male',
            'status' => 'Block',
            'role' => 'Agent',
            'dob' => '09/27/1983',
            'contact_no' => '971557890123',
            'home_address' => 'H # 67, Street 2, Hill Top',
            'email' => 'david.miller@example.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Anna',
            'last_name' => 'Garcia',
            'gender' => 'Female',
            'status' => 'Active',
            'role' => 'Agent',
            'dob' => '02/06/1990',
            'contact_no' => '971558901234',
            'home_address' => 'H # 89, Street 10, Meadow Park',
            'email' => 'anna.garcia@example.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'James',
            'last_name' => 'Martinez',
            'gender' => 'Male',
            'status' => 'Active',
            'role' => 'Guest',
            'dob' => '07/23/1989',
            'contact_no' => '971559012345',
            'home_address' => 'H # 12, Street 3, Sunset Boulevard',
            'email' => 'james.martinez@example.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Laura',
            'last_name' => 'Rodriguez',
            'gender' => 'Female',
            'status' => 'Active',
            'role' => 'Guest',
            'dob' => '04/18/1991',
            'contact_no' => '971560123456',
            'home_address' => 'H # 34, Street 5, Ocean View',
            'email' => 'laura.rodriguez@example.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Paul',
            'last_name' => 'Hernandez',
            'gender' => 'Male',
            'status' => 'Active',
            'role' => 'Guest',
            'dob' => '06/29/1987',
            'contact_no' => '971561234567',
            'home_address' => 'H # 78, Street 7, Woodland Hills',
            'email' => 'paul.hernandez@example.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Olivia',
            'last_name' => 'Garcia',
            'gender' => 'Female',
            'status' => 'Active',
            'role' => 'Agent',
            'dob' => '08/28/1993',
            'contact_no' => '971556789012',
            'home_address' => 'H # 11, Street 5, PECHS',
            'email' => 'olivia@gmail.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Lucas',
            'last_name' => 'Martinez',
            'gender' => 'Male',
            'status' => 'Block',
            'role' => 'Guest',
            'dob' => '07/10/1984',
            'contact_no' => '971501234578',
            'home_address' => 'H # 6, Street 19, Gulberg',
            'email' => 'lucas@gmail.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Ava',
            'last_name' => 'Hernandez',
            'gender' => 'Female',
            'status' => 'Active',
            'role' => 'Staff',
            'dob' => '04/25/1991',
            'contact_no' => '971509876543',
            'home_address' => 'H # 7, Street 23, Model Town',
            'email' => 'ava@gmail.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ],
          [
            'first_name' => 'Alexander',
            'last_name' => 'Lopez',
            'gender' => 'Male',
            'status' => 'Active',
            'role' => 'Staff',
            'dob' => '01/17/1986',
            'contact_no' => '971508765432',
            'home_address' => 'H # 13, Street 16, Korangi',
            'email' => 'alexander@gmail.com',
            'password' => bcrypt('12345678@9'),
            'created_at' => now(),
            'updated_at' => now(),
          ]
        ]);
      } else {
        echo "[User Table is not empty]\n";
      }
    } catch (Exception $e) {
      echo $e->getMessage();
    }
  }
}
